# Generated by Django 2.2.20 on 2021-05-07 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 5, 7, 14, 18, 34, 912310), verbose_name='Опубликовано'),
        ),
    ]
